indentation: tabs

whitelist_rules:
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - empty_parentheses_with_trailing_closure
  - mark
  - modifier_order
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - protocol_property_accessors_order
  - return_arrow_whitespace
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace
  - vertical_whitespace_closing_braces

statement_position:
  statement_mode: uncuddled_else

trailing_whitespace:
  ignores_empty_lines: true
  ignore_comments: true

vertical_whitespace:
  max_empty_lines: 2
